blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'
urlpatterns = [
    path("", blog_views, name='home'),
    path("<int:pid>", single_views, name='single'),
    path("category/<str:cat_name>", blog_views, name='category'),
    path("Tag/<str:tag_name>", blog_views, name='Tag'),
    path("author/<str:author_username>", blog_views, name='author'),
    path("search/", search_views, name='search'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from django.contrib.auth import views as views

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('authenticate/', include('authentication.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots/.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
# Create your models here.


class category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(null=True)
    update_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(auto_now=False)

    def excerpt(self):
        return ' '.join(self.content.split()[:10])+'...'
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid' : self.id})
    
    def __str__(self):
        return self.title

class Meta:
    ordreing = ['-created_date']



class comment(models.Model):
    Poost = models.ForeignKey(post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    messages = models.TextField()
    approved = models.BooleanField(default=False)
    update_date = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name 
         
class Meta:
    ordreing = ['-created_date'] 

 

blog/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, get_object_or_404
from blog.models import post, comment
from datetime import datetime, timedelta
from blog.Form import commentForm
from django.contrib import messages
# Create your views here.


def blog_views(request, **kwargs):
    time_now = datetime.now() + timedelta(days=1)
    formatedDate = time_now.strftime("%Y-%m-%d")
    Posts = post.objects.exclude(published_date__gt=formatedDate).filter(
        status=1).order_by('-created_date')
    if kwargs.get('cat_name') != None:
        Posts = Posts.filter(category__name=kwargs.get('cat_name'))
    if kwargs.get('author_username') != None:
        Posts = Posts.filter(author__username=kwargs.get('author_username'))
    if kwargs.get('tag_name') != None:
        Posts = Posts.filter(tags__name__in=[kwargs.get('tag_name')])
    Posts = Paginator(Posts, 3)
    page_number = request.GET.get('page')
    Posts = Posts.get_page(page_number)
    context = {'Posts': Posts}
    return render(request, 'blog/blog-home.html', context)


def single_views(request, pid):
    time_now = datetime.now() + timedelta(days=1)
    formatedDate = time_now.strftime("%Y-%m-%d")
    Posts = post.objects.exclude(
        published_date__gt=formatedDate).filter(status=1)
    Post = get_object_or_404(Posts, id=pid)
    if request.method == "POST":
        form = commentForm(request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.Poost_id = pid
            comments.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Yor Commets submited successfully')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Yor Commets dident submited.')
    form = commentForm()
    Post.counted_views = Post.counted_views + 1
    Post.save()
    comments = comment.objects.filter(Poost=Post.id, approved=True)
    context = {'Post': Post, 'Posts': Posts,
               'comments': comments, 'form': form}
    return render(request, 'blog/blog-single.html', context)


def search_views(request):
    time_now = datetime.now() + timedelta(days=1)
    formatedDate = time_now.strftime("%Y-%m-%d")
    Posts = post.objects.exclude(
        published_date__gt=formatedDate).filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get("s"):
            Posts = Posts.filter(content__contains=s)
    context = {'Posts': Posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/includes/blog-Ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
	<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

templates/blog/includes/blog-Newsletter.html
{% load static %}
<div class="single-sidebar-widget newsletter-widget">
	<h4 class="newsletter-title">Newsletter</h4>
	<p>
		Here, I focus on a range of items and features that we use in life without
		giving them a second thought.
	</p>
	<div class="form-group d-flex flex-row">
	   <div class="col-autos">
	      <div class="input-group">
	        <div class="input-group-prepend">
	          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
			</div>
	        </div>
	        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
	      </div>
	    </div>
	    <a href="#" class="bbtns">Subcribe</a>
	</div>	
	<p class="text-bottom">
		You can unsubscribe at any time
	</p>								
</div>

templates/blog/includes/blog-Popular-Posts.html
{% load static %}
{% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
	<h4 class="popular-title">Popular Posts</h4>
	<div class="popular-post-list">
	{% for post in posts %}
		<div class="single-post-list d-flex flex-row align-items-center">
			<div class="thumb">
				<img class="img-fluid" src={{post.image.url}} alt=""  style="width:75%;">
			</div>
			<div class="details">
					<a href="{% url 'blog:single' pid=post.id %}"><h6>{{post.title}} </h6></a>
					<p>{{post.published_date|date:"d M"}} </p>
					<p>{{post.published_date|naturaltime}} </p>
			</div>
		</div>
	{% endfor %}														
	</div>
</div>

templates/blog/includes/blog-Post-Catgories.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
	<h4 class="category-title">Post Catgories</h4>
	<ul class="cat-list">
	{% for cat,cunt in category.items %}
		<li>
			<a href="{% url 'blog:category' cat_name=cat %} " class="d-flex justify-content-between">
				<p>{{cat}} </p>
				<p>{{cunt}} </p>
			</a>
		</li>
	{% endfor %}															
	</ul>
</div>

templates/blog/includes/blog-Search.html
<div class="single-sidebar-widget search-widget">
	<form class="search-form" action="{% url 'blog:search' %} " method="GET">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/includes/blog-Tags.html
{% load static %}
<div class="single-sidebar-widget tag-cloud-widget">
	<h4 class="tagcloud-title">Tag Clouds</h4>
	<ul>
	{% for tag in Post.tags.all %}
		<li><a href="{% url 'blog:Tag' tag_name=tag.name %} ">{{tag.name}} </a></li>
	{% endfor %}
	</ul>
</div>

templates/blog/includes/blog-Writer.html
{% load static %}
	<div class="single-sidebar-widget user-info-widget">
		<img src="{% static 'img/blog/user-info.png' %}"" alt="">
		<a href="#"><h4>Charlie Barber</h4></a>
		<p>
			Senior blog writer
		</p>
		<ul class="social-links">
			<li><a href="#"><i class="fa fa-facebook"></i></a></li>
			<li><a href="#"><i class="fa fa-twitter"></i></a></li>
			<li><a href="#"><i class="fa fa-github"></i></a></li>
			<li><a href="#"><i class="fa fa-behance"></i></a></li>
		</ul>
		<p>
			Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
		</p>
	</div>