blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'
urlpatterns = [
    path("", blog_views, name='home'),
    path("<int:pid>", single_views, name='single'),
    path("category/<str:cat_name>", blog_views, name='category'),
    path("Tag/<str:tag_name>", blog_views, name='Tag'),
    path("author/<str:author_username>", blog_views, name='author'),
    path("search/", search_views, name='search'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from django.contrib.auth import views as views

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('authenticate/', include('authentication.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots/.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from website.views import *

app_name = 'website'

urlpatterns = [
    path("", index_views, name='index'),
    path("about", about_views, name='about'),
    path("contact", contact_views, name='contact'),
    path("NEWSLETTER", NEWSLETTER_views, name='NEWSLETTER'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
# Create your models here.


class category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(null=True)
    update_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(auto_now=False)

    def excerpt(self):
        return ' '.join(self.content.split()[:10])+'...'
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid' : self.id})
    
    def __str__(self):
        return self.title

class Meta:
    ordreing = ['-created_date']



class comment(models.Model):
    Poost = models.ForeignKey(post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    messages = models.TextField()
    approved = models.BooleanField(default=False)
    update_date = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name 
         
class Meta:
    ordreing = ['-created_date'] 

 

blog/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, get_object_or_404
from blog.models import post, comment
from datetime import datetime, timedelta
from blog.Form import commentForm
from django.contrib import messages
# Create your views here.


def blog_views(request, **kwargs):
    time_now = datetime.now() + timedelta(days=1)
    formatedDate = time_now.strftime("%Y-%m-%d")
    Posts = post.objects.exclude(published_date__gt=formatedDate).filter(
        status=1).order_by('-created_date')
    if kwargs.get('cat_name') != None:
        Posts = Posts.filter(category__name=kwargs.get('cat_name'))
    if kwargs.get('author_username') != None:
        Posts = Posts.filter(author__username=kwargs.get('author_username'))
    if kwargs.get('tag_name') != None:
        Posts = Posts.filter(tags__name__in=[kwargs.get('tag_name')])
    Posts = Paginator(Posts, 3)
    page_number = request.GET.get('page')
    Posts = Posts.get_page(page_number)
    context = {'Posts': Posts}
    return render(request, 'blog/blog-home.html', context)


def single_views(request, pid):
    time_now = datetime.now() + timedelta(days=1)
    formatedDate = time_now.strftime("%Y-%m-%d")
    Posts = post.objects.exclude(
        published_date__gt=formatedDate).filter(status=1)
    Post = get_object_or_404(Posts, id=pid)
    if request.method == "POST":
        form = commentForm(request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.Poost_id = pid
            comments.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Yor Commets submited successfully')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Yor Commets dident submited.')
    form = commentForm()
    Post.counted_views = Post.counted_views + 1
    Post.save()
    comments = comment.objects.filter(Poost=Post.id, approved=True)
    context = {'Post': Post, 'Posts': Posts,
               'comments': comments, 'form': form}
    return render(request, 'blog/blog-single.html', context)


def search_views(request):
    time_now = datetime.now() + timedelta(days=1)
    formatedDate = time_now.strftime("%Y-%m-%d")
    Posts = post.objects.exclude(
        published_date__gt=formatedDate).filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get("s"):
            Posts = Posts.filter(content__contains=s)
    context = {'Posts': Posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/blog-home.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block content %}  
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">	
	<div class="overlay overlay-bg"></div>
	<div class="container">				
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope				
				</h1>	
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>							
			</div>	
		</div>
	</div>
</section>
<!-- End banner Area -->				
<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">		
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
					    <a href="#" target="_blank">
					      <div class="thumb">
					  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
					  	  </div>
					      <div class="content-details">
					        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
					        <span></span>								        
					        <p>Enjoy your social life together</p>
					      </div>
					    </a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
					    <a href="#" target="_blank">
					      <div class="thumb">
					  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
					  	  </div>
					      <div class="content-details">
					        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
					        <span></span>								        
					        <p>Be a part of politics</p>
					      </div>
					    </a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
					    <a href="#" target="_blank">
					      <div class="thumb">
					  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
					  	  </div>
					      <div class="content-details">
					        <h4 class="content-title mx-auto text-uppercase">Food</h4>
					        <span></span>
					        <p>Let the food be finished</p>
					      </div>
					    </a>
					</div>
				</div>
			</div>												
		</div>
	</div>	
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in Posts %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
						{% for cat in post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last %},{% endif %}</li>
						{% endfor %}	
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}} </a> <span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"d M Y" }} </a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>						
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.image.url}} " alt="">
						</div>
						<a class="posts-title" href="{% url 'blog:single' pid=post.id %}"><h3>{{post.title}} </h3></a>
						<p class="excert">
							<!-- {{post.content|truncatewords:7}} -->
							{{post.excerpt|safe}} <!--Use function excerpt -->
						</p>
						<a href="{% url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}													
                <nav class="blog-pagination justify-content-center d-flex">
                    <ul class="pagination">
					{% if Posts.has_previous %}
                        <li class="page-item">
                            <a href="?page={{ Posts.previous_page_number }}" class="page-link" aria-label="Previous">
                                <span aria-hidden="true">
                                    <span class="lnr lnr-chevron-left"></span>
                                </span>
                            </a>
                        </li>
						{% endif %}
						{% for p in Posts.paginator.page_range %}
						{% if Posts.number == p %}
						<li class="page-item active"><a href="?page={{ p }}" class="page-link">{{p}} </a></li>						
						{% else %}
						<li class="page-item"><a href="?page={{ p }}" class="page-link">{{p}} </a></li>
						{% endif %}
						{% endfor %}
                        {% if Posts.has_next %}
						<li class="page-item">
                            <a href="?page={{ Posts.next_page_number }}" class="page-link" aria-label="Next">
                                <span aria-hidden="true">
                                    <span class="lnr lnr-chevron-right"></span>
                                </span>
                            </a>
                        </li>
						{% endif %}
                    </ul>
                </nav>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
								
								{% include "blog/includes/blog-Search.html" %}

								{% include "blog/includes/blog-Writer.html" %}

								{% popular_post %}

								{% include "blog/includes/blog-Ads.html" %}

								{% category_cunter %}

								{% include "blog/includes/blog-Newsletter.html" %}

				</div>
			</div>
		</div>
	</div>	
</section>
<!-- End post-content Area -->
			
{% endblock  %}	

templates/blog/blog-single.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block content %}  
<!-- start banner Area -->
<section class="relative about-banner">	
	<div class="overlay overlay-bg"></div>
	<div class="container">				
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					Blog Details Page				
				</h1>	
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url 'blog:home' %}">Blog </a> <span class="lnr lnr-arrow-right"></span> <a>{{Post.title}} </a></p>
			</div>	
		</div>
	</div>
</section>
<!-- End banner Area -->					  

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{Post.image.url}} " alt="">
						</div>									
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
						{% for cat in Post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a> {% if not forloop.last %},{% endif %}</li>
						{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">Mark wiens</a> <span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{Post.published_date|date:"d M Y"}} </a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{Post.counted_views|intcomma}} Views</a> <span class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>																				
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{Post.title}} </h3>
						<p class="excert">{{Post.content|safe }}
					</div>
					<div class="col-lg-12">
						<div class="row mt-30 mb-30">
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img1.jpg' %}" alt="">
							</div>
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img2.jpg' %}" alt="">
							</div>	
							<div class="col-lg-12 mt-30">
								<p>
									MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.
								</p>
								<p>
									MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.
								</p>											
							</div>									
						</div>
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
						{% if Post.id > 1 %}
						{% for post in Posts %}
						{% if Post.id|add:"-1" == post.id %}
							<div class="thumb">
								<a href="{% url 'blog:single' pid=post.id %}"><img class="img-fluid" src="{{post.image.url}} " alt="" style="height: 100px;" ></a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								<a href="{% url 'blog:single' pid=post.id %}"><h4>{{post.title}}</h4></a>
							</div>
						{% endif %}
						{% endfor %}
						{% endif %}
						</div>
						<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
						{% if Post.id != Posts|length %}
						{% for post in Posts %}
						{% if Post.id|add:"1" == post.id %}
							<div class="detials">
								<p>Next Post</p>
								<a href="{% url 'blog:single' pid=post.id %}"><h4>{{post.title}}</h4></a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="{% url 'blog:single' pid=post.id %}"><img class="img-fluid" src="{{post.image.url}} " alt="" style="height: 100px;"></a>
							</div>
						{% endif %}
						{% endfor %}
						{% endif %}										
						</div>									
					</div>
				</div>
				<div class="comments-area">
				
					<h4>{{comments|length}} Comments</h4>
					<div class="comment-list">
                        <div class="single-comment justify-content-between d-flex">
						{% for comment in comments %}
                            <div class="user justify-content-between d-flex">
                                <div class="thumb">
                                    <img src="{% static 'img/blog/c1.jpg' %}" alt="">
                                </div>
                                <div class="desc">
                                    <h5><a>{{comment.name}} </a></h5>
                                    <p class="date"> {{comment.created_date}} </p>
                                    <p class="comment" style="font-size:20px">
                                        {{comment.messages}}
                                    </p>
                                </div>
                            </div>
						{% endfor %}
                        </div>
					</div>
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form action="{% url 'blog:single' pid=Post.id %} " method="post">
						{% csrf_token %}
						<div class="form-group form-inline">
						  <div class="form-group col-lg-6 col-md-12 name">
						    <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
						  </div>
						  <div class="form-group col-lg-6 col-md-12 email">
						    <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
						  </div>										
						</div>
						<div class="form-group">
							<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="messages" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
						</div>	
						<p style="float:left" >{{form.captcha}}</p>
						<button class="primary-btn text-uppercase" type="submit" style="left: 10%;">Post Comment</button>	
					</form>
					{% if messages %}
 					{% for message in messages %}
 					<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
 					{% endfor %}
 					{% endif %}
  					{% if form.errors %}
  					<div class="alert alert-error">
  					  <h4>Please fix the following errors</h4>
  					  <ul>
  					    {% for field in form %}
  					      {% if field.errors %}
  					        {% for error in field.errors %}
  					          <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
  					        {% endfor %}
  					      {% endif %}
  					    {% endfor %}
  					  </ul>
  					  {% if form.non_field_errors %}
  					    {{ form.non_field_errors }}
  					  {% endif %}
  					</div>
  					{% endif %}

				</div>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include "blog/includes/blog-Search.html" %}

					{% include "blog/includes/blog-Writer.html" %}

					{% include "blog/includes/blog-Tags.html" %}
					
					{% popular_post %}

					{% include "blog/includes/blog-Ads.html" %}

					{% category_cunter %}

					{% include "blog/includes/blog-Newsletter.html" %}
				</div>
		    </div>
		</div>
	</div>	
</section>
<!-- End post-content Area -->
			
{% endblock  %}	

templates/blog/blog-writer.html
{% load static %}
	<div class="single-sidebar-widget user-info-widget">
		<img src="{% static 'img/blog/user-info.png' %}"" alt="">
		<a href="#"><h4>Charlie Barber</h4></a>
		<p>
			Senior blog writer
		</p>
		<ul class="social-links">
			<li><a href="#"><i class="fa fa-facebook"></i></a></li>
			<li><a href="#"><i class="fa fa-twitter"></i></a></li>
			<li><a href="#"><i class="fa fa-github"></i></a></li>
			<li><a href="#"><i class="fa fa-behance"></i></a></li>
		</ul>
		<p>
			Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
		</p>
	</div>