blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'
urlpatterns = [
    path("", blog_views, name='home'),
    path("<int:pid>", single_views, name='single'),
    path("category/<str:cat_name>", blog_views, name='category'),
    path("Tag/<str:tag_name>", blog_views, name='Tag'),
    path("author/<str:author_username>", blog_views, name='author'),
    path("search/", search_views, name='search'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from django.contrib.auth import views as views

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('authenticate/', include('authentication.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots/.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from website.views import *

app_name = 'website'

urlpatterns = [
    path("", index_views, name='index'),
    path("about", about_views, name='about'),
    path("contact", contact_views, name='contact'),
    path("NEWSLETTER", NEWSLETTER_views, name='NEWSLETTER'),

]

website/models.py
from django.db import models

# Create your models here.


class contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=250,null=True,blank=True,default=None)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Meta:
    ordreing = ['-created_date']



class NEWSLETTER(models.Model):
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

website/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from website.form import ContactForm,NewsletterForm
from django.contrib import messages
# Create your views here.
def index_views(request):
    return render(request,'website/index.html')
    
def about_views(request):
    return render(request,'website/about.html')
    
def contact_views(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.instance.name = form.cleaned_data['name']='UNKNOW'
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Yor ticket submited successfully')
        else:
            messages.add_message(request, messages.ERROR, 'Yor ticket dident submited.')
    form= ContactForm()
    return render(request,'website/contact.html',{'form': form})

def NEWSLETTER_views(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('/')
    form=NewsletterForm()
    return render(request,'website/index.html',{'form': form})

templates/website/includes/home_blog_area.html
{% load static %}
<section class="recent-blog-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-60 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Latest from Our Blog</h1>
					<p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as has.</p>
				</div>
			</div>
		</div>							
		<div class="row">
			<div class="active-recent-blog-carusel">
            {% for post in Posts %}
				<div class="single-recent-blog-post item">
					<div class="thumb">
						<img class="img-fluid" src="{{post.image.url}} " alt=""style="width: 260px;">
					</div>
					<div class="details">
						<div class="tags">
							<ul>
                            {% for cat in post.category.all %}
								<li>
									<a href="{% url 'blog:category' cat_name=cat %} ">{{cat.name}} </a>
								</li>
                            {% endfor %}											
							</ul>
						</div>
						<a href="{% url 'blog:single' pid=post.id %}"><h4 class="title">{{post.title}} </h4></a>
						<p>{{post.content|truncatechars:50 }} </p>
						<h6 class="date">{{post.published_date|date:'d M Y'}} </h6>
					</div>	
				</div>
            {% endfor %}												
			</div>
		</div>
	</div>	
</section>